About kitchen
TikhonenkoVV/mimino pull request #11
Opened 2022-12-03 22:52 UTC by Dmytro-coder

2022-12-04 10:22 UTC, kozhushna commented on src/sass/layouts/_about-kitchen.scss
> +    padding: 16px 0;
Між лементами потрібен margin, до того ж перевір, будь ласка, на всіх версіях відстані, бо на мобілці він 32рх. З іншими фотками також, бо в тебе кругом паддінг

2022-12-04 10:22 UTC, kozhushna commented on src/sass/layouts/_about-kitchen.scss
> +    margin: 12px 0;
Краще використовувати у елементів в потоці якійсь один маржин, чи верхній, чи нижній. Пишу, як нас вчили... На таблеті та десктопі він зовсім інший, зверни увагу - 4 зверху та 24 знизу

2022-12-04 15:44 UTC, TikhonenkoVV commented on src/partials/restaurant/about-kitchen.html
> +    <h1 class="kitchen__title kitchen__title-hidden">ABOUT OUR KITCHEN</h1>
І текст заголовка на українській мові.

2022-12-04 15:47 UTC, TikhonenkoVV commented on src/partials/restaurant/about-kitchen.html
> +        <h2>Amet minim mollit non</h2>
Я б сказав, що це спан, бо текст-риба. В заголовку я думаю написали б щось що має сенс.

2022-12-04 15:47 UTC, TikhonenkoVV commented on src/partials/restaurant/about-kitchen.html
> +        <h3 class="logo">MIMIHO</h3>
Згоден. Я робив спаном.

2022-12-04 15:52 UTC, TikhonenkoVV commented on src/sass/layouts/_about-kitchen.scss
> +    padding: 16px 0;
+

2022-12-05 00:22 UTC, TikhonenkoVV requested changes

2022-12-05 00:22 UTC, TikhonenkoVV commented on src/sass/layouts/_about-kitchen.scss
> +  .container {
На контейнер нічого вішати не можна!!! Додатковий клас якщо потрібно. І про декор я писав у слаку у закріплених повідомленнях.

2022-12-06 11:57 UTC, merged