Origin/room page amenities
TikhonenkoVV/mimino pull request #3
Opened 2022-12-02 21:01 UTC by DyshliukAnna

create html and part scss

2022-12-02 21:06 UTC, DyshliukAnna commented
create html and part scss

2022-12-02 23:53 UTC, TikhonenkoVV requested changes

2022-12-02 23:53 UTC, TikhonenkoVV commented on src/partials/room/amenities.html
> +      <li class="amenities__item">
Клас .amenities__item додай всім лішкам у списку

2022-12-02 23:53 UTC, TikhonenkoVV commented on src/sass/components/room-amenities.scss
> +}
Файл повинен називатись `_room-amenities.scss` 
Файл потрібно імпортувати у index.scss
Додай медіа-запити для таблетки і якщо потрібно для десктопу

2022-12-02 23:53 UTC, TikhonenkoVV commented on src/partials/room/amenities.html
> +        </p>
Там, де є по 2 абзаци - першому додай модифікатор і у стилях тільки для мобільного задай нижній марджин 16px

2022-12-02 23:53 UTC, TikhonenkoVV commented on src/partials/room/amenities.html
> +    <a href="./hotel.html" class="amenities__link">
Додай текст "Повернутися до перегляду номерів"

2022-12-02 23:53 UTC, TikhonenkoVV commented on src/partials/room/amenities.html
> +    </button>
Узгодь з Тетяною Костишин базові стилі кнопок.

2022-12-02 23:53 UTC, TikhonenkoVV commented on src/partials/room/amenities.html
> +        </p>
Винеси заголовок і абзац за межі списку, у них інші стилі.

2022-12-04 14:27 UTC, TikhonenkoVV approved these changes

2022-12-04 15:19 UTC, merged